### ISSUE TITLE
How can i add slider to my website built with mins theme & also changing the footer text

### ISSUE THREAD

**Issue by lohithn4** [godaddy/wp-mins-theme#25]
Hi, 
   I have registered domain with hosting plan in godaddy and selected mins theme & developed silvertongroups.com website, if you visit that website you can see that there is no image slider functionality & i tried to [to post a query at godday community](https://in.godaddy.com/community/Building-and-Managing-a-Website/Enable-header-content-slider-functionality-to-my-webpage-amp/m-p/11137/thread-id/3431) but didn't get proper response so, the main problem is i cann't find any appropriate files in the theme directory to change any header or any part of the website content. It will be great where exactly those header,footer files are present

**Comment by jonathanbardo** [comment]
Hey @lohithn4,

The files are in the parent theme called "Primer". I would strongly suggest you don't modify any of those files though since everytime we send a new update you will see your work being overriden. If you want to modify the CSS you can use a simple plugin to do so https://en-ca.wordpress.org/plugins/simple-custom-css/. If you want to do simple modification you can create a new plugin and move things around but that would require that you know your way around php.

The last option I can recommend is that you create a new child theme that extend the parent theme name "Primer" (https://codex.wordpress.org/Child_Themes) and from there you will have much more flexibility.
