### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by NatzG** [godaddy/wp-mins-theme#27]
Hello, excuse my ignorance, but I'm brand new to GitHub and definitely not a WordPress or PHP dev.  Where can I find documentation supporting this MINS theme?  My site is missing a search box and the header looks nothing like the theme screenshot.  I would also like to remove the theme name in my footer. I feel there are a few basic settings somewhere I'm missing.  Can someone assist please?  Thanks!

**Comment by roenw** [comment]
Well, you're not really supposed to remove the bottom link but I can tell you how. Navigate to the Wordpress Admin page (domain/wp-admin) then go to Appearence > Editor. On the right there is a list of .PHP files. Click on the one that is footer.php. 
Remove the line that says something along the lines of <a href="GitHub">Mins theme</a>

Then save changes.

**Comment by NatzG** [comment]
Thanks for your reply @LionWaffles, but there is no mention of mins in the footer.php file.  That was the first thing I checked before posting here.  I also looked in the functions.php since the footer.php file calls a footer function, but nothing there either.

Why exactly am I not supposed to change the footer line?  If you can point me to where in the TOS or docs it says that, I'd be grateful.

Thanks again.

**Comment by EvanHerman** [comment]
Hi @NatzG ,

We are currently in the process of rolling this theme (and the others) out to WordPress.org, which takes some time. We should have documentation setup properly once all of the themes hit the repository.

To answer your question regarding removing the attribution in the theme footer, you certainly can do that - as it's not against the TOS, and the license that this theme falls under (GPL) allows you to modify the codebase as needed.

You can remove the attribution in the footer by adding a custom function to disable the `primer_author_credit` filter. This would prevent future updates from reverting changes to core theme files, and re-enabling the author credit.

```php
/**
* Disable Primer theme author credits
*
* @return boolean True/False to enable/disable the footer credits.
*/
add_filter( 'primer_author_credit', '__return_false' );
```

You can find the related code in the credit.php file located in [/templates/parts/credit.php](https://github.com/godaddy/wp-primer-theme/blob/develop/templates/parts/credit.php#L27) of the primer parent theme.

**Comment by roenw** [comment]
Actually, it's in the parent theme (Primer.) In most themes there is a terms and conditions or license that says you can use the theme, but you have to give credit in the footer. Not sure if that's the case with Mins, though. 

On Mon, Nov 21, 2016 at 5:43 AM -1000, "NatzG" notifications@github.com wrote:

Thanks for your reply @LionWaffles, but there is no mention of mins in the footer.php file.  That was the first thing I checked before posting here.  I also looked in the functions.php since the footer.php file calls a footer function, but nothing there either.

Why exactly am I not supposed to change the footer line?  If you can point me to where in the TOS or docs it says that, I'd be grateful.

Thanks again.
